# Railway Deployment Configuration
# This file tells Railway how to run your Python backend

[build]
builder = "NIXPACKS"

[deploy]
startCommand = "uvicorn src.arbitrage.web:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Persist strategy database across restarts
[[deploy.volumes]]
mountPath = "/app/data"
name = "strategy_data"
